import { useMemo, useState } from 'react';
import { Download, Search, Camera, FileUp, CheckCircle2, CircleDollarSign } from 'lucide-react';
import type { Invoice } from '../types';
import { exportQuarter } from '../services/exportQuarter';

export function Invoices({invoices,onUpload,onStatusChange}:{invoices:Invoice[];onUpload:()=>void;onStatusChange:(id:string,status:'pending'|'reviewed'|'accounted')=>Promise<void>}){
 const [query,setQuery]=useState(''); const [exporting,setExporting]=useState(false);
 const now=new Date(); const quarter=Math.floor(now.getMonth()/3)+1; const year=now.getFullYear();
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return !q?invoices:invoices.filter(i=>[i.supplierName,i.invoiceNumber,i.category].some(v=>v.toLowerCase().includes(q)))},[invoices,query]);
 const doExport=async()=>{setExporting(true);try{const blob=await exportQuarter(invoices,quarter,year);const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`ZENVIA_Gastos_${quarter}T_${year}.zip`;a.click();URL.revokeObjectURL(url);}finally{setExporting(false)}};
 return <div className="page"><div className="pageHead"><div><div className="eyebrow">DOCUMENTACIÓN</div><h1>Facturas de gastos</h1><p>Sube, revisa y organiza todas las facturas recibidas.</p></div><div className="actions"><button className="secondary" onClick={doExport} disabled={exporting}><Download size={17}/> {exporting?'Preparando…':`Exportar ${quarter}T`}</button><button className="primary" onClick={onUpload}>+ Nueva factura</button></div></div>
 <div className="toolbar"><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar proveedor, nº factura…"/></div></div>
 <section className="card tableCard">{filtered.length?<table><thead><tr><th>Fecha</th><th>Proveedor</th><th>Factura</th><th>Categoría</th><th>Origen</th><th>Estado</th><th className="right">Total</th></tr></thead><tbody>{filtered.map(i=><tr key={i.id}><td>{new Date(`${i.invoiceDate}T12:00:00`).toLocaleDateString('es-ES')}</td><td><strong>{i.supplierName}</strong></td><td>{i.invoiceNumber}</td><td><span className="tag">{i.category}</span></td><td>{i.source==='camera'?<><Camera size={14}/> Cámara</>:i.source==='manual'?<><FileUp size={14}/> Archivo</>:'Gmail'}</td><td><div className="statusActions"><button title="Pendiente" className={i.status==='pending'?'statusBtn active warnBtn':'statusBtn'} onClick={()=>onStatusChange(i.id,'pending')}>P</button><button title="Revisada" className={i.status==='reviewed'?'statusBtn active okBtn':'statusBtn'} onClick={()=>onStatusChange(i.id,'reviewed')}><CheckCircle2 size={13}/></button><button title="Contabilizada" className={i.status==='accounted'?'statusBtn active accountBtn':'statusBtn'} onClick={()=>onStatusChange(i.id,'accounted')}><CircleDollarSign size={13}/></button></div></td><td className="right"><strong>{i.total.toLocaleString('es-ES',{minimumFractionDigits:2})} €</strong></td></tr>)}</tbody></table>:<div className="emptyState large">No hay facturas todavía.</div>}</section></div>
}
