import { useMemo, useState } from 'react';
import { Search, TrendingUp, TrendingDown, AlertTriangle } from 'lucide-react';
import type { Product } from '../types';
export function Products({products,onAdd}:{products:Product[];onAdd:()=>void}){
 const [query,setQuery]=useState(''); const shown=useMemo(()=>{const q=query.toLowerCase().trim();return !q?products:products.filter(p=>[p.name,p.sku??'',p.supplier,p.category??''].some(x=>x.toLowerCase().includes(q)))},[products,query]);
 return <div className="page"><div className="pageHead"><div><div className="eyebrow">INVENTARIO DE COSTES</div><h1>Productos y precios</h1><p>Último coste de compra e histórico actualizado desde las facturas.</p></div><button className="primary" onClick={onAdd}>+ Nuevo producto</button></div>
 <div className="toolbar"><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar producto, SKU o proveedor…"/></div></div>
 <section className="card tableCard">{shown.length?<table><thead><tr><th>Producto</th><th>SKU</th><th>Proveedor</th><th>Última compra</th><th className="right">Precio actual</th><th className="right">Variación</th></tr></thead><tbody>{shown.map(p=>{const delta=p.previousPrice&&p.lastPrice!=null?((p.lastPrice-p.previousPrice)/p.previousPrice)*100:null; return <tr key={p.id}><td><strong>{p.name}</strong><div className="muted">{p.category||'Sin categoría'} · por {p.unit}</div></td><td><span className="mono">{p.sku||'—'}</span></td><td>{p.supplier}</td><td>{p.lastPurchaseDate?new Date(`${p.lastPurchaseDate}T12:00:00`).toLocaleDateString('es-ES'):'—'}</td><td className="right"><strong>{p.lastPrice!=null?`${p.lastPrice.toLocaleString('es-ES',{maximumFractionDigits:4})} €`:'—'}</strong></td><td className="right">{delta==null?<span className="muted">Sin histórico</span>:<span className={delta>0?'delta up':'delta down'}>{delta>0?<TrendingUp size={15}/>:<TrendingDown size={15}/>} {delta>0?'+':''}{delta.toFixed(1)}%</span>}</td></tr>})}</tbody></table>:<div className="emptyState large">Crea el primer producto. Sus precios se irán alimentando desde las facturas de mercancía.</div>}</section>
 <div className="card alertCard"><div className="trendIcon warning"><AlertTriangle/></div><div><h3>Reglas automáticas de actualización</h3><p>Las líneas de producto quedarán vinculadas al producto interno. Si cambia el formato o el precio parece anómalo, podremos exigir confirmación antes de actualizar el coste.</p></div></div></div>
}
