import { useEffect, useState } from 'react';
import { ImageOff, RefreshCw, Search } from 'lucide-react';
import { isAmazonConnectivityError, loadAmazonProductImages, loadAmazonUnmapped, type AmazonPageResult, type AmazonUnmappedSku } from '../../services/amazon';
import { errorMessage } from '../../services/toast';
import { AmazonMappingModal } from './AmazonMappingModal';
import { readViewCache, stableCacheKey, writeViewCache } from '../../services/viewCache';
import { useSettings } from '../../context/SettingsContext';
export function AmazonUnmapped({onChanged,refreshToken=0,defaultConsumptionFactor=1}:{onChanged?:()=>void;refreshToken?:number;defaultConsumptionFactor?:number}){
  const {settings}=useSettings();
  const money=new Intl.NumberFormat('es-ES',{style:'currency',currency:settings.amazon.consolidatedCurrency});
 const [search,setSearch]=useState('');const [page,setPage]=useState(1);const initialKey=stableCacheKey('amazon:unmapped',{search:'',page:1,pageSize:25});const initialData=readViewCache<AmazonPageResult<AmazonUnmappedSku>>(initialKey);const [data,setData]=useState<AmazonPageResult<AmazonUnmappedSku>>(()=>initialData||{items:[],page:1,pageSize:25,total:0});const [loading,setLoading]=useState(()=>!initialData);const [editing,setEditing]=useState<string|null>(null);const [error,setError]=useState('');const [images,setImages]=useState<Record<string,string>>({});
 const refresh=()=>{const key=stableCacheKey('amazon:unmapped',{search,page,pageSize:25});const cached=readViewCache<AmazonPageResult<AmazonUnmappedSku>>(key);if(cached)setData(cached);setLoading(!cached);setError('');return loadAmazonUnmapped(search,page,25).then(next=>{setData(next);writeViewCache(key,next);}).catch(e=>{if(!isAmazonConnectivityError(e))setError(errorMessage(e,'No se pudieron cargar los SKU sin vincular.'));}).finally(()=>setLoading(false));};
 useEffect(()=>{void refresh();},[search,page,refreshToken]);
 useEffect(()=>{const asins=data.items.map(row=>row.asin).filter((value):value is string=>Boolean(value));if(!asins.length){setImages({});return}void loadAmazonProductImages(asins).then(setImages).catch(()=>setImages({}));},[data.items]);
 const editingRow=editing?data.items.find(row=>row.sellerSku===editing):undefined;
 return <section className="card amazonTableCard"><div className="amazonTableToolbar"><div><span className="amazonSectionLabel">CALIDAD DE DATOS</span><strong>Sin vincular</strong><p>Relaciona cada SKU de Amazon con su Producto interno y define el Factor de consumo para packs o bundles.</p></div><label className="amazonSearch"><Search size={16}/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Buscar SKU o ASIN"/></label></div>{error&&<div className="amazonQueryError amazonQueryErrorInline"><span>{error}</span><button className="secondary" onClick={()=>void refresh()}><RefreshCw size={14}/> Reintentar</button></div>}<div className="amazonTableScroll"><table className="amazonTable amazonUnmappedTable"><thead><tr><th>Producto Amazon</th><th>Marketplaces</th><th>Pedidos</th><th>Unidades</th><th>Ventas recientes</th><th></th></tr></thead><tbody>{data.items.map(row=><tr key={row.sellerSku}><td><div className="amazonProductIdentity">{row.asin&&images[row.asin]?<img className="amazonProductThumb" src={images[row.asin]} alt="" loading="lazy" referrerPolicy="no-referrer"/>:<span className="amazonProductThumb amazonProductThumbPlaceholder"><ImageOff size={18}/></span>}<div><strong>{row.sellerSku}</strong><small>{row.asin||'ASIN no disponible'}</small></div></div></td><td>{row.marketplaceIds.join(', ')}</td><td>{row.orders}</td><td>{row.units}</td><td>{money.format(row.recentNetSales)}</td><td><button className="amazonInlineAction" onClick={()=>setEditing(row.sellerSku)}>Vincular</button></td></tr>)}{!data.items.length&&<tr><td colSpan={6} className="amazonEmptyCell">{loading?'Cargando SKU sin vincular…':'Todos los SKU detectados están vinculados.'}</td></tr>}</tbody></table></div>{editing&&<AmazonMappingModal sellerSku={editing} asin={editingRow?.asin} imageUrl={editingRow?.asin?images[editingRow.asin]||null:null} initialFactor={defaultConsumptionFactor} onSaved={()=>{setEditing(null);void refresh();onChanged?.();}} onClose={()=>setEditing(null)}/>}<div className="amazonPagination"><span>{loading&&!data.items.length?'Cargando SKU…':`${data.total} SKU pendientes`}</span><div><button disabled={page<=1} onClick={()=>setPage(v=>v-1)}>Anterior</button><span>Página {page}</span><button disabled={page*25>=data.total} onClick={()=>setPage(v=>v+1)}>Siguiente</button></div></div></section>;
}
