import { useEffect, useState } from 'react';
import { RefreshCw, Search } from 'lucide-react';
import { loadAmazonUnmapped, type AmazonPageResult, type AmazonUnmappedSku } from '../../services/amazon';
import { errorMessage } from '../../services/toast';
import { AmazonMappingEditor } from './AmazonMappingEditor';
const money=new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'});
export function AmazonUnmapped({onChanged,refreshToken=0}:{onChanged?:()=>void;refreshToken?:number}){
 const [data,setData]=useState<AmazonPageResult<AmazonUnmappedSku>>({items:[],page:1,pageSize:25,total:0});const [search,setSearch]=useState('');const [page,setPage]=useState(1);const [editing,setEditing]=useState<string|null>(null);const [error,setError]=useState('');
 const refresh=()=>{setError('');return loadAmazonUnmapped(search,page,25).then(setData).catch(e=>setError(errorMessage(e,'No se pudieron cargar los SKU sin vincular.')));};
 useEffect(()=>{void refresh();},[search,page,refreshToken]);
 return <section className="card amazonTableCard"><div className="amazonTableToolbar"><div><span className="amazonSectionLabel">CALIDAD DE DATOS</span><strong>Sin vincular</strong><p>Relaciona cada SKU de Amazon con su Producto interno y define el Factor de consumo para packs o bundles.</p></div><label className="amazonSearch"><Search size={16}/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Buscar SKU o ASIN"/></label></div>{error&&<div className="amazonQueryError amazonQueryErrorInline"><span>{error}</span><button className="secondary" onClick={()=>void refresh()}><RefreshCw size={14}/> Reintentar</button></div>}<div className="amazonTableScroll"><table className="amazonTable"><thead><tr><th>SKU</th><th>ASIN</th><th>Marketplaces</th><th>Pedidos</th><th>Unidades</th><th>Ventas recientes</th><th></th></tr></thead><tbody>{data.items.map(row=><tr key={row.sellerSku}><td><strong>{row.sellerSku}</strong></td><td>{row.asin||'—'}</td><td>{row.marketplaceIds.join(', ')}</td><td>{row.orders}</td><td>{row.units}</td><td>{money.format(row.recentNetSales)}</td><td><button className="amazonInlineAction" onClick={()=>setEditing(editing===row.sellerSku?null:row.sellerSku)}>Vincular</button></td></tr>)}{!data.items.length&&<tr><td colSpan={7} className="amazonEmptyCell">Todos los SKU detectados están vinculados.</td></tr>}</tbody></table></div>{editing&&<div className="amazonInlineEditor"><AmazonMappingEditor sellerSku={editing} onSaved={()=>{setEditing(null);void refresh();onChanged?.();}} onCancel={()=>setEditing(null)}/></div>}<div className="amazonPagination"><span>{data.total} SKU pendientes</span><div><button disabled={page<=1} onClick={()=>setPage(v=>v-1)}>Anterior</button><span>Página {page}</span><button disabled={page*25>=data.total} onClick={()=>setPage(v=>v+1)}>Siguiente</button></div></div></section>;
}
