import { useEffect, useState } from 'react';
import { RefreshCw, Search } from 'lucide-react';
import { loadAmazonInventory, type AmazonAnalyticsFilters, type AmazonInventoryAnalytics, type AmazonMarketplaceStatus, type AmazonPageResult } from '../../services/amazon';
import { errorMessage } from '../../services/toast';
import { formatAmazonMarketplace } from './marketplaceLabel';
export function AmazonInventory({filters,marketplaces,refreshToken=0}:{filters:AmazonAnalyticsFilters;marketplaces:AmazonMarketplaceStatus[];refreshToken?:number}){
 const [data,setData]=useState<AmazonPageResult<AmazonInventoryAnalytics>>({items:[],page:1,pageSize:25,total:0});const [search,setSearch]=useState('');const [page,setPage]=useState(1);const [error,setError]=useState('');
 const refresh=()=>{setError('');return loadAmazonInventory(filters,search,page,25).then(setData).catch(e=>setError(errorMessage(e,'No se pudo cargar el inventario.')));};
 useEffect(()=>{void refresh();},[filters.marketplaceIds.join(','),search,page,refreshToken]);
 return <section className="card amazonTableCard"><div className="amazonTableToolbar"><div><span className="amazonSectionLabel">FBA</span><strong>Inventario</strong></div><label className="amazonSearch"><Search size={16}/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Buscar SKU o ASIN"/></label></div>{error&&<div className="amazonQueryError amazonQueryErrorInline"><span>{error}</span><button className="secondary" onClick={()=>void refresh()}><RefreshCw size={14}/> Reintentar</button></div>}<div className="amazonTableScroll"><table className="amazonTable"><thead><tr><th>SKU</th><th>Marketplace</th><th>Disponible</th><th>Reservado</th><th>Entrante</th><th>No disponible</th><th>Investigando</th><th>Total</th><th>Última sync</th></tr></thead><tbody>{data.items.map(row=><tr key={`${row.marketplaceId}-${row.sellerSku}`}><td><strong>{row.sellerSku}</strong><small>{row.asin||'—'}</small></td><td>{formatAmazonMarketplace(row.marketplaceId,marketplaces)}</td><td>{row.fulfillable}</td><td>{row.reserved}</td><td>{row.inbound}</td><td>{row.unfulfillable}</td><td>{row.researching}</td><td><strong>{row.total}</strong></td><td>{new Date(row.lastSync).toLocaleString('es-ES')}</td></tr>)}{!data.items.length&&<tr><td colSpan={9} className="amazonEmptyCell">No hay inventario sincronizado.</td></tr>}</tbody></table></div><div className="amazonPagination"><span>{data.total} posiciones</span><div><button disabled={page<=1} onClick={()=>setPage(v=>v-1)}>Anterior</button><span>Página {page}</span><button disabled={page*25>=data.total} onClick={()=>setPage(v=>v+1)}>Siguiente</button></div></div></section>;
}
