import { useEffect, useState } from 'react';
import { ImageOff, RefreshCw, Search } from 'lucide-react';
import { isAmazonConnectivityError, loadAmazonInventory, loadAmazonProductImages, type AmazonAnalyticsFilters, type AmazonInventoryAnalytics, type AmazonMarketplaceStatus, type AmazonPageResult } from '../../services/amazon';
import { errorMessage } from '../../services/toast';
import { formatAmazonMarketplace } from './marketplaceLabel';
import { readViewCache, stableCacheKey, writeViewCache } from '../../services/viewCache';
export function AmazonInventory({filters,marketplaces,refreshToken=0}:{filters:AmazonAnalyticsFilters;marketplaces:AmazonMarketplaceStatus[];refreshToken?:number}){
 const [search,setSearch]=useState('');const [page,setPage]=useState(1);const initialKey=stableCacheKey('amazon:inventory',{marketplaceIds:filters.marketplaceIds,search:'',page:1,pageSize:25});const [data,setData]=useState<AmazonPageResult<AmazonInventoryAnalytics>>(()=>readViewCache<AmazonPageResult<AmazonInventoryAnalytics>>(initialKey)||{items:[],page:1,pageSize:25,total:0});const [error,setError]=useState('');const [images,setImages]=useState<Record<string,string>>({});
 const refresh=()=>{const key=stableCacheKey('amazon:inventory',{marketplaceIds:filters.marketplaceIds,search,page,pageSize:25});const cached=readViewCache<AmazonPageResult<AmazonInventoryAnalytics>>(key);if(cached)setData(cached);setError('');return loadAmazonInventory(filters,search,page,25).then(next=>{setData(next);writeViewCache(key,next);}).catch(e=>{if(!isAmazonConnectivityError(e))setError(errorMessage(e,'No se pudo cargar el inventario.'));});};
 useEffect(()=>{void refresh();},[filters.marketplaceIds.join(','),search,page,refreshToken]);
 useEffect(()=>{const asins=data.items.map(row=>row.asin).filter((value):value is string=>Boolean(value));if(!asins.length){setImages({});return}void loadAmazonProductImages(asins).then(setImages).catch(()=>setImages({}));},[data.items]);
 return <section className="card amazonTableCard"><div className="amazonTableToolbar"><div><span className="amazonSectionLabel">FBA</span><strong>Inventario</strong></div><label className="amazonSearch"><Search size={16}/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Buscar SKU o ASIN"/></label></div>{error&&<div className="amazonQueryError amazonQueryErrorInline"><span>{error}</span><button className="secondary" onClick={()=>void refresh()}><RefreshCw size={14}/> Reintentar</button></div>}<div className="amazonTableScroll"><table className="amazonTable"><thead><tr><th>SKU</th><th>Marketplace</th><th>Disponible</th><th>Reservado</th><th>Entrante</th><th>No disponible</th><th>Investigando</th><th>Total</th><th>Última sync</th></tr></thead><tbody>{data.items.map(row=><tr key={`${row.marketplaceId}-${row.sellerSku}`}><td><div className="amazonProductIdentity">{row.asin&&images[row.asin]?<img className="amazonProductThumb" src={images[row.asin]} alt="" loading="lazy" referrerPolicy="no-referrer"/>:<span className="amazonProductThumb amazonProductThumbPlaceholder"><ImageOff size={18}/></span>}<div><strong>{row.sellerSku}</strong><small>{row.asin||'ASIN no disponible'}</small></div></div></td><td>{formatAmazonMarketplace(row.marketplaceId,marketplaces)}</td><td>{row.fulfillable}</td><td>{row.reserved}</td><td>{row.inbound}</td><td>{row.unfulfillable}</td><td>{row.researching}</td><td><strong>{row.total}</strong></td><td>{new Date(row.lastSync).toLocaleString('es-ES')}</td></tr>)}{!data.items.length&&<tr><td colSpan={9} className="amazonEmptyCell">No hay inventario sincronizado.</td></tr>}</tbody></table></div><div className="amazonPagination"><span>{data.total} posiciones</span><div><button disabled={page<=1} onClick={()=>setPage(v=>v-1)}>Anterior</button><span>Página {page}</span><button disabled={page*25>=data.total} onClick={()=>setPage(v=>v+1)}>Siguiente</button></div></div></section>;
}
