import { useEffect, useState } from 'react';
import { RefreshCw, Search } from 'lucide-react';
import { isAmazonConnectivityError, loadAmazonOrders, type AmazonAnalyticsFilters, type AmazonMarketplaceStatus, type AmazonOrderAnalytics, type AmazonPageResult } from '../../services/amazon';
import { errorMessage } from '../../services/toast';
import { formatAmazonMarketplace } from './marketplaceLabel';
import { readViewCache, stableCacheKey, writeViewCache } from '../../services/viewCache';
const money=new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'});
export function AmazonOrders({filters,marketplaces,refreshToken=0}:{filters:AmazonAnalyticsFilters;marketplaces:AmazonMarketplaceStatus[];refreshToken?:number}){
 const [search,setSearch]=useState('');const [page,setPage]=useState(1);const initialKey=stableCacheKey('amazon:orders',{filters,search:'',page:1,pageSize:25});const [data,setData]=useState<AmazonPageResult<AmazonOrderAnalytics>>(()=>readViewCache<AmazonPageResult<AmazonOrderAnalytics>>(initialKey)||{items:[],page:1,pageSize:25,total:0});const [error,setError]=useState('');
 const refresh=()=>{const key=stableCacheKey('amazon:orders',{filters,search,page,pageSize:25});const cached=readViewCache<AmazonPageResult<AmazonOrderAnalytics>>(key);if(cached)setData(cached);setError('');return loadAmazonOrders(filters,search,page,25).then(next=>{setData(next);writeViewCache(key,next);}).catch(e=>{if(!isAmazonConnectivityError(e))setError(errorMessage(e,'No se pudieron cargar los pedidos.'));});};
 useEffect(()=>{void refresh();},[filters.from,filters.to,filters.marketplaceIds.join(','),search,page,refreshToken]);
 return <section className="card amazonTableCard"><div className="amazonTableToolbar"><div><span className="amazonSectionLabel">PEDIDOS</span><strong>Detalle de pedidos</strong></div><label className="amazonSearch"><Search size={16}/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Buscar pedido"/></label></div>{error&&<div className="amazonQueryError amazonQueryErrorInline"><span>{error}</span><button className="secondary" onClick={()=>void refresh()}><RefreshCw size={14}/> Reintentar</button></div>}<div className="amazonTableScroll"><table className="amazonTable"><thead><tr><th>Pedido</th><th>Fecha</th><th>Marketplace</th><th>Estado</th><th>Unidades</th><th>Ventas</th><th>Tarifas</th><th>Coste</th><th>Beneficio</th></tr></thead><tbody>{data.items.map(row=><tr key={`${row.marketplaceId}-${row.amazonOrderId}`}><td><strong>{row.amazonOrderId}</strong></td><td>{new Date(row.purchaseDate).toLocaleDateString('es-ES')}</td><td>{formatAmazonMarketplace(row.marketplaceId,marketplaces)}</td><td>{row.status||'—'}</td><td>{row.units}</td><td>{money.format(row.netSales)}</td><td>{money.format(row.amazonFees)}</td><td>{money.format(row.productCost)}</td><td>{money.format(row.profitBeforeAds)}{!row.profitComplete&&<small className="amazonIncomplete">Incompleto</small>}</td></tr>)}{!data.items.length&&<tr><td colSpan={9} className="amazonEmptyCell">No hay pedidos para este periodo.</td></tr>}</tbody></table></div><div className="amazonPagination"><span>{data.total} pedidos</span><div><button disabled={page<=1} onClick={()=>setPage(v=>v-1)}>Anterior</button><span>Página {page}</span><button disabled={page*25>=data.total} onClick={()=>setPage(v=>v+1)}>Siguiente</button></div></div></section>;
}
