import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './styles.css';
import './enhancements.css';
import './gmail.css';
import './mobile-nav.css';
import './gmail-mobile.css';
import './gmail-preview.css';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
