import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './styles.css';
import './enhancements.css';
import './sidebar-brand.css';
import './gmail.css';
import './gmail-filter.css';
import './mobile-nav.css';
import './gmail-mobile.css';
import './gmail-preview.css';
import './history-theme.css';
import './mobile-session.css';
import './toast.css';
import './validation.css';
import './pagination.css';
import './readability.css';
import './modal-sticky-fix.css';
import './sales-config.css';
import './master-data.css';
import './supplier-period.css';
import './orders.css';
import './orders-status.css';
import './orders-edit.css';
import './orders-products.css';
import './orders-tracking.css';
import './dashboard-summary.css';
import './interface-normalization.css';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
