create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  workspace_owner_id uuid not null references auth.users(id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  actor_email text,
  module text not null,
  action text not null,
  entity_type text not null,
  entity_id text,
  entity_label text,
  summary text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_logs_workspace_created_idx on public.audit_logs(workspace_owner_id, created_at desc);
create index if not exists audit_logs_actor_created_idx on public.audit_logs(actor_user_id, created_at desc);
create index if not exists audit_logs_module_created_idx on public.audit_logs(module, created_at desc);

alter table public.audit_logs enable row level security;
revoke all on public.audit_logs from anon;
revoke insert, update, delete on public.audit_logs from authenticated;
grant select on public.audit_logs to authenticated;

drop policy if exists audit_logs_admin_select on public.audit_logs;
create policy audit_logs_admin_select on public.audit_logs
for select to authenticated
using (
  workspace_owner_id = (select private.app_workspace_owner_id())
  and (select private.app_is_admin())
);

create or replace function private.audit_app_change()
returns trigger
language plpgsql
security definer
set search_path = public, pg_catalog
as $$
declare
  before_row jsonb;
  after_row jsonb;
  row_data jsonb;
  workspace_id uuid;
  actor_id uuid;
  actor_mail text;
  module_name text;
  action_name text;
  entity_kind text;
  entity_key text;
  entity_name text;
  message text;
  safe_details jsonb := '{}'::jsonb;
begin
  before_row := case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) else '{}'::jsonb end;
  after_row := case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) else '{}'::jsonb end;
  row_data := case when tg_op = 'DELETE' then before_row else after_row end;
  actor_id := auth.uid();
  entity_kind := tg_table_name;

  if tg_table_name = 'gmail_imports' and tg_op = 'INSERT' then return new; end if;
  if tg_table_name = 'gmail_imports' and tg_op = 'UPDATE' and old.status is not distinct from new.status then return new; end if;

  workspace_id := nullif(row_data->>'owner_id','')::uuid;
  if workspace_id is null then workspace_id := private.app_workspace_owner_id(); end if;
  if workspace_id is null then if tg_op = 'DELETE' then return old; else return new; end if; end if;
  if actor_id is not null then select au.email into actor_mail from public.app_users au where au.user_id = actor_id limit 1; end if;
  entity_key := coalesce(row_data->>'id', row_data->>'user_id');

  if tg_table_name = 'invoices' then
    module_name := 'invoices'; entity_name := coalesce(row_data->>'invoice_number', row_data->>'file_name', 'Sin número');
    safe_details := jsonb_strip_nulls(jsonb_build_object('invoice_number',row_data->>'invoice_number','issue_date',row_data->>'issue_date','supplier_id',row_data->>'supplier_id','category_id',row_data->>'expense_category_id','total',row_data->>'total_amount','status',row_data->>'status','source',row_data->>'source','file_name',row_data->>'file_name'));
    if tg_op = 'INSERT' then action_name := case when row_data->>'source'='gmail' then 'import' else 'create' end; message := case when row_data->>'source'='gmail' then 'Importó la factura ' else 'Creó la factura ' end || entity_name;
    elsif tg_op = 'DELETE' then action_name := 'delete'; message := 'Eliminó la factura ' || entity_name;
    elsif old.status is distinct from new.status then action_name := 'status_change'; message := 'Cambió el estado de la factura ' || entity_name || ' de ' || coalesce(old.status,'—') || ' a ' || coalesce(new.status,'—'); safe_details := safe_details || jsonb_build_object('previous_status',old.status,'new_status',new.status);
    else action_name := 'update'; message := 'Modificó la factura ' || entity_name; end if;

  elsif tg_table_name = 'products' then
    module_name := 'products'; entity_name := coalesce(row_data->>'name','Producto');
    safe_details := jsonb_strip_nulls(jsonb_build_object('name',row_data->>'name','sku',row_data->>'sku','category',row_data->>'category','unit',row_data->>'base_unit','price',row_data->>'last_cost','previous_price',row_data->>'previous_cost'));
    if tg_op = 'INSERT' then action_name := 'create'; message := 'Creó el producto ' || entity_name;
    elsif tg_op = 'DELETE' then action_name := 'delete'; message := 'Eliminó el producto ' || entity_name;
    elsif old.last_cost is distinct from new.last_cost and old.name is not distinct from new.name and old.sku is not distinct from new.sku and old.category is not distinct from new.category and old.base_unit is not distinct from new.base_unit and old.active is not distinct from new.active then action_name := 'price_update'; message := 'Actualizó el precio de ' || entity_name || ' de ' || coalesce(old.last_cost::text,'—') || ' € a ' || coalesce(new.last_cost::text,'—') || ' €'; safe_details := safe_details || jsonb_build_object('previous_price',old.last_cost,'new_price',new.last_cost);
    else action_name := 'update'; message := 'Modificó el producto ' || entity_name; end if;

  elsif tg_table_name = 'suppliers' then
    module_name := 'suppliers'; entity_name := coalesce(row_data->>'name','Proveedor');
    safe_details := jsonb_strip_nulls(jsonb_build_object('name',row_data->>'name','tax_id',row_data->>'tax_id','email',row_data->>'email','supplier_type',row_data->>'supplier_type','active',row_data->>'active'));
    if tg_op = 'INSERT' then action_name := 'create'; message := 'Creó el proveedor ' || entity_name;
    elsif tg_op = 'DELETE' then action_name := 'delete'; message := 'Eliminó el proveedor ' || entity_name;
    else action_name := 'update'; message := 'Modificó el proveedor ' || entity_name; end if;

  elsif tg_table_name = 'gmail_imports' then
    module_name := 'gmail'; entity_name := coalesce(row_data->>'attachment_name',row_data->>'subject','Adjunto de Gmail');
    safe_details := jsonb_strip_nulls(jsonb_build_object('attachment_name',row_data->>'attachment_name','subject',row_data->>'subject','sender',row_data->>'sender','previous_status',before_row->>'status','new_status',after_row->>'status','invoice_id',row_data->>'invoice_id'));
    action_name := case after_row->>'status' when 'imported' then 'import' when 'ignored' then 'ignore' when 'found' then 'recover' when 'error' then 'error' else 'update' end;
    message := case after_row->>'status' when 'imported' then 'Marcó como importado '||entity_name when 'ignored' then 'Ignoró '||entity_name when 'found' then 'Recuperó '||entity_name||' para revisión' when 'error' then 'La importación de '||entity_name||' terminó con error' else 'Actualizó '||entity_name end;

  elsif tg_table_name = 'export_runs' then
    if tg_op <> 'INSERT' then if tg_op='DELETE' then return old; else return new; end if; end if;
    module_name := 'invoices'; action_name := 'export'; entity_name := (row_data->>'fiscal_quarter')||'T '||(row_data->>'fiscal_year'); message := 'Exportó '||coalesce(entity_name,'facturas');
    safe_details := jsonb_strip_nulls(jsonb_build_object('fiscal_year',row_data->>'fiscal_year','fiscal_quarter',row_data->>'fiscal_quarter','invoice_count',row_data->>'invoice_count','total_amount',row_data->>'total_amount'));
  else
    if tg_op='DELETE' then return old; else return new; end if;
  end if;

  insert into public.audit_logs(workspace_owner_id,actor_user_id,actor_email,module,action,entity_type,entity_id,entity_label,summary,details)
  values(workspace_id,actor_id,actor_mail,module_name,action_name,entity_kind,entity_key,entity_name,message,safe_details);
  if tg_op='DELETE' then return old; else return new; end if;
end;
$$;

revoke all on function private.audit_app_change() from public, anon, authenticated;

drop trigger if exists audit_invoices on public.invoices;
create trigger audit_invoices after insert or update or delete on public.invoices for each row execute function private.audit_app_change();
drop trigger if exists audit_products on public.products;
create trigger audit_products after insert or update or delete on public.products for each row execute function private.audit_app_change();
drop trigger if exists audit_suppliers on public.suppliers;
create trigger audit_suppliers after insert or update or delete on public.suppliers for each row execute function private.audit_app_change();
drop trigger if exists audit_gmail_imports on public.gmail_imports;
create trigger audit_gmail_imports after insert or update or delete on public.gmail_imports for each row execute function private.audit_app_change();
drop trigger if exists audit_export_runs on public.export_runs;
create trigger audit_export_runs after insert or update or delete on public.export_runs for each row execute function private.audit_app_change();
